### ISSUE TITLE
Add Gryphatrice-Jubilant

### ISSUE THREAD

**Issue by melvio** [melvio/hopla#235]
```
Traceback (most recent call last):
  File "/home/m/.local/bin/hopla", line 8, in <module>
    sys.exit(setup_hopla_application())
  File "/home/m/.local/lib/python3.8/site-packages/hopla/__init__.py", line 29, in setup_hopla_application
    kickstart_hopla()
  File "/home/m/.local/lib/python3.8/site-packages/hopla/kickstart.py", line 160, in kickstart_hopla
    hopla()
  File "/home/m/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/m/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/m/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/m/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/m/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/m/.local/lib/python3.8/site-packages/hopla/cli/feed_all.py", line 98, in feed_all
    plan: FeedPlan = __get_feed_plan_or_exit()
  File "/home/m/.local/lib/python3.8/site-packages/hopla/cli/feed_all.py", line 27, in __get_feed_plan_or_exit
    zoo: Zoo = ZooBuilder(user).build()
  File "/home/m/.local/lib/python3.8/site-packages/hopla/hoplalib/zoo/zoomodels.py", line 81, in build
    pet = Pet(pet_name, feed_status=FeedStatus(feed_status))
  File "/home/m/.local/lib/python3.8/site-packages/hopla/hoplalib/zoo/petmodels.py", line 40, in __init__
    raise InvalidPet(f"{pet_name=} is not recognized by hopla.\n"
hopla.hoplalib.zoo.petmodels.InvalidPet: pet_name='Gryphatrice-Jubilant' is not recognized by hopla.
Potential causes: 
* did you spell it correctly?
* Is your pet relatively new? If so, please raise
 an issue at https://github.com/melvio/hopla/issues/new
```

**Comment by melvio** [comment]
closed, duplicate of #234
